### ISSUE TITLE
In vuestorefront , After stripe-payment payment integration " order not placing issue "

### ISSUE THREAD

**Issue by manojibcarockers** [develodesign/vsf-payment-stripe#19]
I trying stripe-payment integration with vuestorefront
i complete integration follow through this link:" https://github.com/develodesign/vsf-payment-stripe "
After integration, I try to check payment process so i use test-card for payment.
But payment is show two notification error:
1,Error: Error placing an order
2,The order can not be transfered because of server error. Order has been queued
Do you know anything about this issue?

**Comment by collymore** [comment]
Hi, this is because there is no payment method configured in Magento that supports the payment method code 'stripe' that's used. 

Please take a look at the simple payment method we created and update the code to match 'stripe' https://github.com/develodesign/m2-paypal-payment 

We're working on a new version that will include support the backend of the official Magento 2 stripe plugin, so refunds and order canceling can happen from Magento.
